### PR TITLE
addresses: unspents value should be in satoshis

### LINKED ISSUE #4: addresses.unspents value in bitcoins
Will be in satoshis:

actual response

``` js
[ { address: '12U6eu3sD8AWsrhqWc3Xq93MqnYAfSwiiU',
    confirmations: 41,
    vout: 0,
    txId: '2f4dfd806ef7b04ef195619c16f140742c89707b10a49db2a6b937640556b0c4',
    value: '0.73223700' } ]
```

``` js
[ { txId: '2f4dfd806ef7b04ef195619c16f140742c89707b10a49db2a6b937640556b0c4',
    address: '12U6eu3sD8AWsrhqWc3Xq93MqnYAfSwiiU',
    confirmations: 41,
    value: 73223700,
    vout: 0 } ]
```

### PR DESCRIPTION
**Pull request by dcousens**
(Hopefully) fixes #4

Lets see what travis says

### CODE REVIEW

**Comment by dcousens** [comment]
Updated `common-blockchain` to `0.2.0` as well because it has basic type checking all the return values as well, which would have at least caught part of this.

**Comment by weilu** [comment]
common-blockchain did not define value should be in satoshi or otherwise. So technically #4 isn't a bug, it's a feature. Upgrading to `cb-tester` 0.2.x resulted in a lot of non-TODO test failures. I'd like to address all of those at some point. @dcousens I think we should allow tests to be explicitly skipped to allow a green build even with unimplemented endpoints. Those unimplemented endpoints should definitely be documented explicitly on the readme of cb-foo.

**Comment by dcousens** [comment]
Agreed on the ability to opt-out of things where the end points just don't or can't exist; however you shouldn't be able to skip tests just because the implementation is failing them.

As for satoshis, perhaps that wasn't clear in the documentation, but that was meant to always be the case.  I'll fix that now as its an obviously undocumented aspect of the API.

**Comment by weilu** [comment]
> however you shouldn't be able to skip tests just because the implementation is failing them.

Of course, that goes without saying.

> As for satoshis, perhaps that wasn't clear in the documentation, but that was meant to always be the case.

cb-blockr is guilty too. `value` has always meant to be in BTC and I didn't document it.

**Comment by dcousens** [comment]
Any chance of merging this?

**Comment by weilu** [comment]
Not yet. I need to pass all cb-tester 0.1.x tests before upgrading to 0.2

**Pull request closed without merging**
